[package]
name = "cn-tigerbeetle"
version = "0.1.2"
edition = "2021"
description = "Cloud-native TigerBeetle client for Rust with DNS-based service discovery"
license = "Apache-2.0"
authors = ["TigerBeetle, Inc", "Krishnacore"]
homepage = "https://github.com/krishnacore/tigerbeetle"
repository = "https://github.com/krishnacore/tigerbeetle"
documentation = "https://docs.rs/tigerbeetle"
keywords = ["finance", "accounting", "ledger", "database", "kubernetes"]
categories = ["finance", "database"]
rust-version = "1.63"
# Need to do this to pick up the assets directory and exclude zig files
include = [
  "build.rs",
  "src/*.rs",
  "assets/tb_client.h",
  "assets/lib/*/{*.a,*.lib}",
]

[dependencies]
bitflags = "2.6.0"
futures-channel = "0.3.31"

[build-dependencies]
anyhow = "1.0.93"

[dev-dependencies]
anyhow = "1.0.93"
futures = "0.3.31"
