name: Release
permissions: {}

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      packages: write
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: release # Use the 'release' branch even if triggered manually

      # Rust: publish with the oldest supported release to ensure compatible lockfiles etc.
      - run: rustup default 1.63 && rustup component add clippy rustfmt

      - run: ./zig/download.sh

      - name: Build and publish Docker
        run: ./zig/zig build scripts -- release --build --publish --sha=${{ github.sha }} --language=docker
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and publish Rust client
        run: ./zig/zig build scripts -- release --build --publish --sha=${{ github.sha }} --language=rust
        env:
          CRATES_IO_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  alert_failure:
    runs-on: ubuntu-latest
    needs: [release]
    if: ${{ always() && contains(needs.*.result, 'failure') }}
    steps:
      - name: Alert if anything failed
        run: |
          export URL="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" && \
          curl -d "text=Release process for ${{ github.run_number }} failed! See ${URL} for more information." -d "channel=C04RWHT9EP5" -H "Authorization: Bearer ${{ secrets.SLACK_TOKEN }}" -X POST https://slack.com/api/chat.postMessage
